### ISSUE TITLE
Button capture reset after changing any setting

### ISSUE THREAD

**Issue by babybambula** [automadcms/automad-dist#3]
I want to use a button in the Main content of a page.
Adding and renaming the button capture, check.
But when I go into the settings menu and change any attribute, the capture changes back to the initial value ("Button" or "Enter text ...").
When you enter the URL value, start typing already resets the capture.
Other values (like color, URL, ...) persist.

**Comment by marcantondahmen** [comment]
This is the distribution repository. Please read the readme or documentation regarding opening issues.
